### ISSUE TITLE
Corrispondenza con i dati officiali

### ISSUE THREAD

**Issue by alessiolombini** [floatingpurr/ita-vax-analytics#1]
Ciao,

Innanzitutto grazie mille per fornire questi ! Vorrei chiedere se questi dati si basano su una serie storica dei dati officiali o se sono costruiti sui dati giornalieri.

**Comment by floatingpurr** [comment]
Ciao. I dati provengono dalle rilevazioni giornaliere puntuali rilasciate ufficialmente. In questo repo, i dati grezzi sono aggregati con diverse strategie, così da fornire le statistiche che mi sono sembrate comuni, senza bisogno di rifare i conti.

**Comment by floatingpurr** [comment]
Per il momento chiudo. Se avessi altre curiosità, sentiti assolutamente libero di aprire una nuova [discussione](https://github.com/floatingpurr/ita-vax-analytics/discussions). Ciao!
